### ISSUE TITLE
C++ Builder Support

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/python4delphi#172]
Provide C++ Builder packages and update the C++ Builder demos.

I am not using and have no experience with C++ Builder, so help on this will be appreciated.

- [ ] C++ Builder packages
- [ ] Demo 18
- [ ] Demo 19
- [ ] Demo 20

**Comment by pyscripter** [comment]
Added link to the [blog post](https://davidiontools.com/2020/10/13/using-python4delphi-with-cbuilder-vcl-applications/) by David Intersimone

**Comment by minguyen1984** [comment]
Hi pyscripter,

What kind of help do you need? I changed the Python_D.dproj to generate C++ header file and lib,
Now I work exclusively on C++ project after the resolution of MaskFPUExceptions in August.

minguyen

**Comment by pyscripter** [comment]
@minguyen1984  You can update  C++ demos 18-20 if you can.

Demo 18 does not use P4D and links directly to the appropriate python lib
Demo 19 and 20 use P4D.  
    - Demo 20 also links to the python lib file, but I think this can avoided since P4D includes the python API.

It would be nice to convert demos 19 and 20 to use only P4D and not the Pyhtonxy.lib.  Demo 18 can be dropped.


Also a wiki page with installation instructions for C++Builder would also be helpful.  Have a look at the linked [blog post](https://davidiontools.com/2020/10/13/using-python4delphi-with-cbuilder-vcl-applications/) by David Intersimone.

**Comment by minguyen1984** [comment]
Ok to drop Demo18 which is a console application.
Demo19 is OK.

But for Demo20 (based on Demo08 delphi code), we have a problem in the method PyArg_ParseTuple of TPythonInterface class:

Delphi declaration 
        PyArg_ParseTuple:   function( args: PPyObject; format: PAnsiChar {;...}): Integer; cdecl varargs;

C++ declaration:
	int __cdecl (*PyArg_ParseTuple)(PPyObject args, char * format);

Python declaration:
        int PyArg_ParseTuple(PyObject *arg, char *format, ...);

So now for C++, we can't use PyArg_ParseTuple function which as 2 arguments instead of several for python/delphi declaration. "vargars" is the issue.

search in progress...

**Comment by pyscripter** [comment]
PyArg_ParseTuple is a very common function in P4D. Can we fix the C++ declaration?

**Comment by minguyen1984** [comment]
Basically, yes.
Just after my last message, I tested the solution to "modify" the C++ declaration into:
        int __cdecl (*PyArg_ParseTuple)(PPyObject args, char * format, ...); 
in the header .hpp file. Variadic function is also available for C++

The compilation is ok and the execution too.
To be honest, this modification is really not the good solution.

Maybe we have an option somewhere to make the accurate translation during the Python_D compilation.

**Comment by minguyen1984** [comment]
Hello,
To generate the C++ header and lib files, just active the options (Delphi compiler -> Output C/C++) in the Python_D project:

![image](https://user-images.githubusercontent.com/69810107/97724184-e6a29f80-1acc-11eb-9c26-9a8f25d0c122.png)

Files are generated by default in the folder:
C:\Users\Public\Documents\Embarcadero\Studio\19.0\hpp for hpp files
C:\Users\Public\Documents\Embarcadero\Studio\19.0\DCP for bpi, dcp and lib files

*19.0 for Tokyo

Moreover, Pythonengine.pas is modified with (PythonEngine.zip):
- WRITE_RESTRICTED flags is renamed to PY_WRITE_RESTRICTED because WRITE_RESTRICTED already exist in windows SDK include file winnt.h, 
- Adding some directive to export the 4 functions of class TPythionInterface using varargs (thanks you very much to Embarcadero support)


And the two updated demo19 and demo20 (Demos19-20.zip), work with Tokyo but i think no problem with Rio and Sydney.


[PythonEngine.zip](https://github.com/pyscripter/python4delphi/files/5465995/PythonEngine.zip)
[Demos19-20.zip](https://github.com/pyscripter/python4delphi/files/5465998/Demos19-20.zip)

**Comment by pyscripter** [comment]
Your changes have been merged to master.  Thanks a lot!
I am closing this issue.

But, could you please submit a PR to replace the binary form files for Demos 19-10 with text form files?  That way you will be entered as a project contributor.
