### ISSUE TITLE
Bug: "input" gives strange result

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/python4delphi#30]
```
What steps will reproduce the problem?
1. In program "console" (my prog has it) I enter "print(input('Test'))"
2. In dialog I enter "Про"

What is the expected output? 
Dialog with label named "Test". And output line "Про".

What do you see instead?
Dialog with label "Enter text". And output line "TestПро". Surprise.

What version of the product are you using? On what operating system?
Delphi7, WinXP SP3, Py3.2.5, Py4D 3.32(last one)

```

Original issue reported on code.google.com by `ato...@gmail.com` on 26 Dec 2013 at 6:49

**Comment by pyscripter** [comment]
That's how Python input works.
say you execute
`input("Please enter number :")
`
Python write to the stdout "Please enter number :" and waits for input from stdin.  When P4D receives the requst for input there is no way of knowing what the prompt was.  So you are presented with an input box with a generic prompt.   Say you type in the input box "123", then the output would look:

Please enter number : 123

To change this behaviour you can overwrite the python input function.  You can also use the event of TPythonInputOutput OnReceiveData to modify what happens when python expects input.
