### ISSUE TITLE
Demo25 does not compile or fails during running

### ISSUE THREAD

**Issue by c722181** [pyscripter/python4delphi#391]
I am using Delphi-XE7 on Windows-11
I have installed Python 3.11.1 and Python4Delphi
Running Demo01 gives no problems
But running Demo25 (with VarPyth) gives Error 87:  could not open Dll "python34.dll"
This happens when compiled for Win32. 
It seems that CPUX86 is enabled, so it looks for Python 3.11-32 in the registry which is not present
But somehow CPUX86 is not enabled in Demo01

Compiling Demo25 for Win64 gives:
E2089, invalid TypeCast for  TPythonVarData(Result).VType := VarPython; 
in VarPythonCreate, plus a bunch of similar errors on other lines.
So it seems that a 64 bit Variant under 64 bits cannot be typecasted to TPythonVarData, whereas under 32 bits this is not a problem. Very strange to me.

**Comment by pyscripter** [comment]
Please check out the following:

[FindingPython · pyscripter/python4delphi Wiki (github.com)](https://github.com/pyscripter/python4delphi/wiki/FindingPython)

and set up your PythonEngine accordingly.

If you plant to use P4D with 64-Python you need to compile your Delphi program in 64-bits.   CPUX86 is set because you are compiling in 32 bits.  It is a Delphi directive.
