### ISSUE TITLE
<urlopen error unknown url type: https>

### ISSUE THREAD

**Issue by dima72** [pyscripter/python4delphi#407]
Hi, 
In python4Delphi VCL application, I'm getting error 
**urlopen error unknown url type: https** 
on any **https** request or **http** that remote server turns response into https. 
e.g
```
import urllib.request
request_url = urllib.request.urlopen('https://google.com')
print(request_url.read())

```
However, in python's console in OS https requests work fine.

I've made sure SSL library is installed well : _conda install -c anaconda openssl_
I copied SSL libraries(libcrypto-1_1.dll, libssl-1_1.dll) into application's folder too, but no success. 

Please support me on this issue.

**Comment by pyscripter** [comment]
Have you searched the web for "urlopen error unknown url type: https"?
e.g. https://stackoverflow.com/questions/28376506/urllib-https-request-urlopen-error-unknown-url-type-https

This is likely a python installation issue and not a P4D issue.

Please use the support forum instead of the issue tracker.

**Comment by dima72** [comment]
my problem has solved!

Sorry I did not mention, I'm running anaconda 32bit.
I highly probably was caused previous anaconda64 installations or 64bit SSL packages.

so, **I installed Miniconda32 and running Python4Delphi application from there.**
and https works fine now.

thanks for guidance!
