### ISSUE TITLE
Demo14: SystemError: initialization of database failed without raising an exception

### ISSUE THREAD

**Issue by danieleteti** [pyscripter/python4delphi#58]
Hi,

using the library project (compiled as `pyd`) of the `Demo14`, I get the following error when try to load the `database` module from the python console:

```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import database
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: initialization of database failed without raising an exception

```

The behavior is the same also coping `database.pyd` in Python' Lib folder.
Considering that I don't have the BDE installed, I removed the `pyDBTables.pas` reference in the sources of `pyDB.pas` and `pyDatabase.pas`.

**Comment by pyscripter** [comment]
The pyDB and pyDatabase stuff is deprecated and not supported.  It has been replaced by the WrapFireDAC unit.  See Demo10_FireDAC for how it can be used.  
In any case Demo14 is not compatible with python3.  See in Demo09 how to write a DLL that is compatible with python3.  The name of the initialization function needs to be PyInit_demodll instead of procedure initdemodll.
