### ISSUE TITLE
Is it possible to create python list that content is tuple using VarPythonCreate?

### ISSUE THREAD

**Issue by kalmenchia** [pyscripter/python4delphi#66]
Hi , can i check whether we can create a python list = [("name","=","Kelvin"),("title","=","MR"),...] 
using VarPythonCreate  ? Or is there any where we can do that ? 

For your information the list has to be created in Delphi and pass it back to a python class
to get evaluated and then return the result back to Delphi app.

Thanks.

**Comment by pyscripter** [comment]
You can use the following to create lists or tuples
```pascal
function VarPythonCreate( const AValues : array of const; ASequenceType : TSequenceType = stList ) : Variant; overload;
```

You could also use 

```pascal
function VarPythonEval( const APythonExpression : AnsiString) : Variant;
```
e.g VarPythonEval('[("name","=","Kelvin"),("title","=","MR")]')

**Comment by pyscripter** [comment]
Your original question did not mention TPythonDelphiVar and the like.  

TPythonDelphiVar allows you to export simple Delphi values to Python.  
VarPyth on the other hand is about manipulating Python objects in Delphi. (high-level)
WrapDelphi is about wrapping Delphi objects and exposing to Python.
**Look at the numerous demos and study the code.**

Assigning a custom variant to a TPythonDelphiVar.Value is not supported:
   list1.value := VarPythonEval('[("name","=","Kelvin"),("title","=","MR")]');
Only simple variant types will work.

On the other hand you may try:
  list1.ValueObject := ExtractPythonObjectFrom(VarPythonEval('[("name","=","Kelvin"),("title","=","MR")]'));
might work.

Instead of using a TPythonDelphiVar you can just add a TPythonModule and use the SetVar method.

Finally please do not use the issue tracker to ask for support.  Use Stackoverflow, Delphi forums etc.

**Comment by kalmenchia** [comment]
Hi , thanks for your kind advice despite of support requests which i reported because i think as i suspected that it is an issue of P4D , please do allow me to ask one last question which may indicate the potential of creating a complex python's List with content of tuple(s) that may caused issues , here is what i found out ,

1. as mentioned , i wish to create using Delphi for python list 
   [("name","=","Kelvin"),("title","=","MR")]
2. i have tried for all methods , VarPythonEval , VarPythonCreate or any suggested
3. i found out that the "expected" list was not created instead it created something
    like this in my backend , it is a tuple instead of list ,
   ([["name","=","Kelvin"],["title","=","MR"]],)

is this the issue of P4D ?

**Comment by pyscripter** [comment]
VarPythonEval('[("name","=","Kelvin"),("title","=","MR")]')
or just
GetPythonEngine.EvalString('[("name","=","Kelvin"),("title","=","MR")]')

creates a list of tuples.   This is python, nothing to do with P4D.

You can use
function VarPythonCreate( const AValues : array of const; ASequenceType : TSequenceType = stList ) : Variant; overload;
to create either a list or a tuple depending on the second parameter.
